// Generated by dts-bundle v0.2.0

declare module 'cu-ui-boilerplate-library' {
    import BoilerplateModuleImport = require('__cu-ui-boilerplate-library/boilerplate-module/boilerplate-module');
    export class BoilerplateLibrary {
        static BoilerplateModule: typeof BoilerplateModuleImport.BoilerplateModule;
    }
}

declare module '__cu-ui-boilerplate-library/boilerplate-module/boilerplate-module' {
    export class BoilerplateModule {
        constructor();
        sayHello(): void;
        static staticSayHello(): void;
    }
}

