// Generated by dts-bundle v0.2.0

declare module 'library' {
    import boilerplateModule = require('__library/boilerplate-module/boilerplate-module');
    export module BoilerplateLibrary {
        export import BoilerplateModule = boilerplateModule.BoilerplateModule;
    }
}

declare module '__library/boilerplate-module/boilerplate-module' {
    export class BoilerplateModule {
        constructor();
        sayHello(): void;
        static staticSayHello(): void;
    }
}

